Part1
luke-den/PFMCPP_Project2 pull request #1
Opened 2022-06-02 22:12 UTC by luke-den

2022-06-02 23:12 UTC, matkatmusic requested changes

2022-06-02 23:12 UTC, matkatmusic commented on main.cpp
> +{
Fix this error
- [ ] revise

2022-06-02 23:12 UTC, matkatmusic commented on main.cpp
> +    double eqModesShown = 6;
Don't initialize doubles with integers.
write doubles correctly. 
`4.0` is a double.  `4` is an integer
- [ ] revise

2022-06-02 23:18 UTC, matkatmusic requested changes
Every single function name you chose is a noun.  No verbs were used in the function names, which means they are not describing actions.

2022-06-02 23:18 UTC, matkatmusic commented on main.cpp
> +    double
fix this issue with the `^M`
- [ ] revise

2022-06-02 23:18 UTC, matkatmusic commented on main.cpp
> +bool lowPassFilter(int slopeType = 2, float cutoffFreq = 100.0f)
This function name does not conform to the programming guideline:
```
Name Things what they are.
Name Actions based on what they do
```
The name you chose reflects a property (noun) and does not contain a verb, which would reflect an action.
Functions perform work, so their names must contain a verb which describes the work being performed.
Examples of function names that contain verbs:
- `computeAValue()`
- `estimateDistanceTraveled()`
- `performDiagnostics()`

- [ ] revise

2022-06-02 23:18 UTC, matkatmusic commented on main.cpp
> +int distanceWalkedToday(int numbOfSteps, float milesPerHour = 12.3f)
This function name does not conform to the programming guideline:
```
Name Things what they are.
Name Actions based on what they do
```
The name you chose reflects a property (noun) and does not contain a verb, which would reflect an action.
Functions perform work, so their names must contain a verb which describes the work being performed.
Examples of function names that contain verbs:
- `computeAValue()`
- `estimateDistanceTraveled()`
- `performDiagnostics()`

- [ ] revise

2022-06-02 23:18 UTC, matkatmusic commented on main.cpp
> +float initFrequency(bool sawtoothWave, bool squareWave, bool sineWave)
- [ ] revise: function name

2022-06-02 23:18 UTC, matkatmusic commented on main.cpp
> +double stepLength(int beatDivision, int timeSignature, bool tempoMatching = true)
- [ ] revise: function name

2022-06-02 23:18 UTC, matkatmusic commented on main.cpp
> +int busEffects(bool reverbOn = true, bool delayOn = false, int wetDryMix = 50)
- [ ] revise: function name

2022-06-02 23:18 UTC, matkatmusic commented on main.cpp
> +//6)void defaultLoopLength(int defaultMeasures, int defaultNumOfBeats)
- [ ] revise: function name

2022-06-02 23:18 UTC, matkatmusic commented on main.cpp
> +int totalNumOfTracks(int audioTracks, int midiTracks)
- [ ] revise: function name

2022-06-02 23:18 UTC, matkatmusic commented on main.cpp
> +double equipmentBudget(float percentageOfIncome = 49.9f, int analogSynths = 4, int programmingCourses = 10)
- [ ] revise: function name

2022-06-02 23:18 UTC, matkatmusic commented on main.cpp
> +int hamburgersEaten(int withFries = 3, int withoutFries = 2, float withOnions = 0.5f)
- [ ] revise: function name

2022-06-02 23:18 UTC, matkatmusic commented on main.cpp
> +void fastFoodReceipts(int mcdonalds = 3, int wendys = 2, int carlsJr = 1)
- [ ] revise: function name

2022-06-03 14:22 UTC, luke-den commented on main.cpp
> +bool lowPassFilter(int slopeType = 2, float cutoffFreq = 100.0f)
Doh!

2022-06-03 23:19 UTC, matkatmusic approved these changes

2022-06-03 23:19 UTC, merged